server:
  port: 8080

spring:
  main:
    allow-bean-definition-overriding: true
  data:
    cassandra:
      contact-points: 172.31.79.226,172.31.91.44,172.31.94.106
      cluster-name: Test Cluster
      port: 9042
      keyspace-name: books
      password: cassandra
      username: cassandra
      consistency-level: local_quorum

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG

management:
  endpoints:
    jmx:
      exposure:
        include: '*'
  endpoint:
    metrics:
      enabled: true
  metrics:
    export:
      jmx:
        enabled: true
