server:
  port: 10001

spring:
  main:
    allow-bean-definition-overriding: true
  data:
    cassandra:
      contact-points:
      cluster-name: Test Cluster


logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG

